import { Router } from 'express';
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
import { logShadowAudit } from './shadowLogger';

const router = Router();

// Cuentas Bancarias
router.get('/:condominioId/cuentas', async (req, res) => {
  try {
    const cuentas = await prisma.cuentaBancaria.findMany({
      where: { condominioId: req.params.condominioId }
    });
    res.json(cuentas);
  } catch (error) {
    res.status(500).json({ error: 'Error' });
  }
});

router.post('/:condominioId/cuentas', async (req, res) => {
  try {
    const { nombre, tipo, saldoUSD, saldoVES } = req.body;
    const cuenta = await prisma.cuentaBancaria.create({
      data: {
        condominioId: req.params.condominioId,
        nombre, tipo, saldoUSD: Number(saldoUSD), saldoVES: Number(saldoVES)
      }
    });
    res.json(cuenta);
  } catch (error) {
    res.status(500).json({ error: 'Error' });
  }
});

router.put('/:condominioId/cuentas/:cuentaId', async (req, res) => {
  try {
    const { nombre, tipo, saldoUSD, saldoVES } = req.body;
    const cuenta = await prisma.cuentaBancaria.update({
      where: { id: req.params.cuentaId },
      data: { nombre, tipo, saldoUSD: Number(saldoUSD), saldoVES: Number(saldoVES) }
    });
    res.json(cuenta);
  } catch (error) {
    res.status(500).json({ error: 'Error' });
  }
});

router.delete('/:condominioId/cuentas/:cuentaId', async (req, res) => {
  try {
    await prisma.cuentaBancaria.delete({ where: { id: req.params.cuentaId } });
    res.json({ ok: true });
  } catch (error) {
    res.status(500).json({ error: 'Error' });
  }
});

// Fondo de Reserva
router.get('/:condominioId/fondo', async (req, res) => {
  try {
    const fondo = await prisma.fondoReserva.findUnique({
      where: { condominioId: req.params.condominioId }
    });
    res.json(fondo);
  } catch (error) {
    res.status(500).json({ error: 'Error' });
  }
});

router.post('/:condominioId/fondo', async (req, res) => {
  try {
    const { saldoUSD, porcentaje } = req.body;
    const fondo = await prisma.fondoReserva.upsert({
      where: { condominioId: req.params.condominioId },
      update: { saldoUSD: Number(saldoUSD), porcentaje: Number(porcentaje) },
      create: {
        condominioId: req.params.condominioId,
        saldoUSD: Number(saldoUSD),
        porcentaje: Number(porcentaje)
      }
    });
    res.json(fondo);
  } catch (error) {
    res.status(500).json({ error: 'Error' });
  }
});

// Pagos
router.get('/:condominioId/pagos', async (req, res) => {
  try {
    const pagos = await prisma.pago.findMany({
      include: { aviso: true }
    });
    res.json(pagos);
  } catch (error) {
    res.status(500).json({ error: 'Error' });
  }
});

router.post('/:condominioId/pagos', async (req, res) => {
  try {
    const { avisoId, montoPagado, moneda, referencia } = req.body;
    const actorId = (req as any).user?.id || 'SISTEMA';

    const result = await prisma.$transaction(async (tx) => {
      // 1. Fetch notice and its payments
      const aviso = await tx.avisoCobro.findUnique({
        where: { id: avisoId },
        include: { pagos: true }
      });

      if (!aviso) {
        throw new Error('Aviso de cobro no encontrado');
      }

      // 2. Create the payment
      const pago = await tx.pago.create({
        data: { avisoId, montoPagado: Number(montoPagado), moneda, referencia }
      });

      // 3. Recalculate total paid
      let totalPagadoUSD = 0;
      for (const p of aviso.pagos) {
        if (p.moneda === 'USD') totalPagadoUSD += p.montoPagado;
        else if (p.moneda === 'VES') totalPagadoUSD += p.montoPagado / aviso.tasaBCV;
      }
      
      // Add current payment
      if (moneda === 'USD') totalPagadoUSD += Number(montoPagado);
      else if (moneda === 'VES') totalPagadoUSD += Number(montoPagado) / aviso.tasaBCV;

      const epsilon = 0.01;
      const isPaid = totalPagadoUSD >= (aviso.montoUSD - epsilon);

      // 4. Update Notice
      await tx.avisoCobro.update({
        where: { id: avisoId },
        data: { pagado: isPaid }
      });

      // 5. System WORM Log
      const sysLog = await tx.logSistema.create({
        data: {
          condominioId: req.params.condominioId,
          tipo: 'PAGO',
          mensaje: `Abono de ${montoPagado} ${moneda} registrado (Ref: ${referencia})`,
          usuarioId: actorId,
          accion: 'CREATE',
          entidadAfectada: 'Pago',
          datosNuevos: JSON.stringify({ avisoId, montoPagado, moneda, isPaid }),
          hashIntegridad: '' // Will be generated by Shadow Logger
        }
      });

      return { pago, sysLog };
    });

    // 6. Escribir en Log Sombra (Out-of-Band)
    const hash = logShadowAudit({
      usuarioId: actorId,
      accion: 'CREATE',
      entidadAfectada: 'Pago',
      datosNuevos: result.pago,
      mensaje: `Abono de ${montoPagado} ${moneda} registrado (Ref: ${referencia})`
    });

    // Update the DB log with the generated hash
    await prisma.logSistema.update({
      where: { id: result.sysLog.id },
      data: { hashIntegridad: hash }
    });

    res.json(result.pago);
  } catch (error: any) {
    res.status(500).json({ error: error.message || 'Error' });
  }
});

// Estado de Cuentas (Cobranzas)
router.get('/:condominioId/estado-cuentas', async (req, res) => {
  try {
    const avisos = await prisma.avisoCobro.findMany({
      where: { propiedad: { condominioId: req.params.condominioId } },
      include: { 
        propiedad: { include: { residentes: true } }, 
        pagos: true 
      }
    });

    const propiedadesMap = new Map();

    for (const aviso of avisos) {
      const propId = aviso.propiedadId;
      if (!propiedadesMap.has(propId)) {
        propiedadesMap.set(propId, {
          propiedadId: propId,
          numero: aviso.propiedad.numero,
          residente: aviso.propiedad.residentes[0]?.nombre || 'Sin residente',
          mesesDeuda: 0,
          totalDeudaUSD: 0,
          totalDeudaVES: 0,
          avisosPendientes: []
        });
      }

      const pData = propiedadesMap.get(propId);

      if (!aviso.pagado) {
        let abonadoUSD = 0;
        let abonadoVES = 0;
        aviso.pagos.forEach(p => {
          if (p.moneda === 'USD') { abonadoUSD += p.montoPagado; abonadoVES += p.montoPagado * aviso.tasaBCV; }
          else { abonadoVES += p.montoPagado; abonadoUSD += p.montoPagado / aviso.tasaBCV; }
        });

        const deudaRestanteUSD = aviso.montoUSD - abonadoUSD;
        const deudaRestanteVES = aviso.montoVES - abonadoVES;

        if (deudaRestanteUSD > 0) {
          pData.mesesDeuda += 1;
          pData.totalDeudaUSD += deudaRestanteUSD;
          pData.totalDeudaVES += deudaRestanteVES;
          pData.avisosPendientes.push({
            ...aviso,
            abonadoUSD,
            abonadoVES,
            deudaRestanteUSD,
            deudaRestanteVES
          });
        }
      }
    }

    res.json(Array.from(propiedadesMap.values()));
  } catch (error) {
    res.status(500).json({ error: 'Error al calcular estado de cuentas' });
  }
});

export default router;
